[package]
name = "server"
version = "0.1.0"
authors = ["sawmurai <fabian.becker@b-it-d.de>"]
edition = "2018"

[dependencies]
tokio = "0.1.22"
tokio-io = "0.1.4"
tokio-core = "0.1.17"
rust-ini = "0.13"
argparse = "0.2.2"

futures = "0.1.21"
worklog = { path = "../worklog" }
