[global.databases]
sqlite_wlog = { url = "/data/wlog.sqlite" }

[development]
address = "localhost"
port = 8001
workers = 1
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }
sqlite_wlog = { url = "/tmp/wlog.sqlite" }

[staging]
address = "0.0.0.0"
port = 8001
workers = 1
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8001
workers = 1
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
